name: Build and publish Pages

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    - name: Gradle Check
      run: ./gradlew check

    - name: Gradle Assemble
      run: ./gradlew assemble

    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4.2.3
      with:
        branch: pages
        folder: build/distributions
